### PR TITLE
Add FedEx special services

### PR DESCRIPTION
**Pull request by nisevi**
Add FedEx special services

The intention of this PR is to add the same functionality it was provided by this branch https://github.com/yorikim/active_shipping/commit/87fc38ca3322b3b28035644fe8e36c7718afd81c but to merge it finally into master branch 👍 

In that way we will be able to pull the gem by just doing:

```ruby
gem 'active_shipping', github: 'team-eden/active_shipping'
```

and not how it is being done now:

```ruby
gem 'active_shipping', github: 'team-eden/active_shipping', branch: 'ik/features/special-services', ref: '87fc38c
```

The reason is that we need to make another PR to modify master and allow `active_shipping` to support `activesupport` versions greater or equal to `5.2.0` when upgrading rails to version `5.2.0`

image

image

image

So next upgrade should be something like `activesupport < 6, >= 4.2`, and we can't depend anymore on just this branch https://github.com/yorikim/active_shipping/commit/87fc38ca3322b3b28035644fe8e36c7718afd81c

### CODE REVIEW

**Review by bruz — APPROVED** [review]
👍

**Comment by gilesbowkett** [comment]
I think it'd be wise to update the gemspec also with this change. there's another change I've been meaning to make in this gem forever, and since we're maintaining this separately from the main repo (which if I recall correctly is no longer supported), I think it'd be a real good idea to bump the gem version with every change. @bruz @nisevi what do you think?

**Comment by bruz** [comment]
@gilesbowkett if we reference the gem from github as proposed by @nisevi:

```
gem 'active_shipping', github: 'team-eden/active_shipping'
```

Then the SHA we're locked at is tracked in papaya's Gemfile.lock, I believe? And an upgrade would involve either `gem update active_shipping` to get to the latest, or if we want to lock it to an old SHA we'd have to add a `ref: '<SHA here>'` in the Gemfile.

If we specify versions, would we also need to publish the gem, either through rubygems (since it's a public repo) or gemfury? It's a bit more ceremony, but one argument for it I can see is that sequential versions are easier to compare than SHAs, and it's also what we do for mango and pomegranate. It looks like we do have some forked libraries where we're just referencing the github repo without gem versioning: obfuscate_id, fiscali and omniauth-23andme.

**Comment by gilesbowkett** [comment]
yikes. I think the repo shouldn't be public if we're discussing what version of Rails our app is on (for security reasons). I almost posted specifics about stuff I want to change in our app in my previous comment, so thanks for mentioning the public factor. it's MIT license, so we can take it private if we want.  I think it'd be good karma to keep maintaining it publicly, but [the way GitHub handles abandoned projects](https://github.com/hubotio/hubot/issues/953#issuecomment-109472535), it's kind of useless.

anyway, I think what said @nisevi said about referencing the repo in the Gemfile is fine. I don't want to add version numbers in our app's Gemfile, so maybe adding version numbers in the gemspec is useless too, I just feel like it ought to be a little more organized somehow.

**Review by gilesbowkett — APPROVED** [review]
nvm, go ahead 👍

**Pull request merged**
